### PR TITLE
Integer and fixed point squared roots

### LINKED ISSUE #99: Distance function ignores east-west map wrapping
The function below (from Province.cpp) does not appear to take into account the east-west wrapping of the map. It will yield incorrectly large distances between provinces on the west edge of the map and those on the east edge.

```
Province::distance_t Province::calculate_distance_to(Province const* province) const {
	const fvec2_t my_unit_position = get_unit_position();
	const fvec2_t other_unit_position = province->get_unit_position();
	const fvec2_t distance_vector = other_unit_position - my_unit_position;
	const fixed_point_t distance = distance_vector.length_squared();
	return static_cast<Province::distance_t>(distance);
}
```

### PR DESCRIPTION
**Pull request by zaaarf**
Implemented [this](https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Binary_numeral_system_(base_2)) simple deterministic algorithm.

...and since now we can, I fixed #99 in the other commit.

### CODE REVIEW

File: src/openvic-simulation/map/Province.cpp [hunk 1]
```diff
@@ -1,6 +1,10 @@
 #include "Province.hpp"
 
 #include "openvic-simulation/history/ProvinceHistory.hpp"
+#include "openvic-simulation/map/Map.hpp"
+#include "types/Vector.hpp"
+#include "types/fixed_point/FixedPoint.hpp"
```
Comment (Spartan322) [inline src/openvic-simulation/map/Province.cpp:6]:
```suggestion
#include "openvic-simulation/types/Vector.hpp"
#include "openvic-simulation/types/fixed_point/FixedPoint.hpp"
```

Comment (zaaarf) [reply src/openvic-simulation/map/Province.cpp:6]: AAAAAAA

File: src/openvic-simulation/map/Map.hpp [hunk 2]
```diff
@@ -5,6 +5,7 @@
 
 #include <openvic-dataloader/csv/LineObject.hpp>
 
+#include "map/Province.hpp"
```
Comment (Hop311) [inline src/openvic-simulation/map/Map.hpp:8]:
```suggestion
#include "openvic-simulation/map/Province.hpp"
```

File: src/openvic-simulation/map/Map.hpp [hunk 3]
```diff
@@ -89,6 +90,13 @@ namespace OpenVic {
 		bool add_province(std::string_view identifier, colour_t colour);
 		IDENTIFIER_REGISTRY_NON_CONST_ACCESSORS_CUSTOM_INDEX_OFFSET(province, 1);
 
+		Province::distance_t calculate_distance_between(Province const& from, Province const& to);
+		bool add_standard_adjacency(Province& from, Province& to);
+		bool add_special_adjacency(
+			Province& from, Province& to, Province::adjacency_t::type_t type, Province const* through,
+			Province::adjacency_t::data_t data
+		);
```
Comment (Hop311) [inline src/openvic-simulation/map/Map.hpp:98]:
```suggestion
		Province::distance_t calculate_distance_between(Province const& from, Province const& to) const;
		bool add_standard_adjacency(Province& from, Province& to) const;
		bool add_special_adjacency(
			Province& from, Province& to, Province::adjacency_t::type_t type, Province const* through,
			Province::adjacency_t::data_t data
		) const;
```

File: src/openvic-simulation/map/Province.cpp [hunk 4]
```diff
@@ -1,6 +1,7 @@
 #include "Province.hpp"
 
 #include "openvic-simulation/history/ProvinceHistory.hpp"
+#include <algorithm>
```
Comment (Hop311) [inline src/openvic-simulation/map/Province.cpp:4]: I think this is leftover from when you were using `std::min` here, can you remove it since it's not needed anymore

File: src/openvic-simulation/map/Map.cpp [hunk 5]
```diff
@@ -69,6 +69,173 @@ bool Map::add_province(std::string_view identifier, colour_t colour) {
...
 
+Province::distance_t Map::calculate_distance_between(Province const& from, Province const& to) {
+	const fvec2_t to_pos = to.get_unit_position();
+	const fvec2_t from_pos = from.get_unit_position();
+
+	const fixed_point_t min_x = std::min(
+		to_pos.x - from_pos.x,
+		std::min(
+			to_pos.x - from_pos.x + width,
+			to_pos.x - from_pos.x - width
```
Comment (Hop311) [inline src/openvic-simulation/map/Map.cpp:80]:
```suggestion
		(to_pos.x - from_pos.x).abs(),
		std::min(
			(to_pos.x - from_pos.x + width).abs(),
			(to_pos.x - from_pos.x - width).abs()
```
We need to take the absolute value otherwise it'll select large negative ones.

**Review by Hop311 — COMMENTED** [review]
As well as the comments below, the fixed point sqrt function is always returning `0.9999847412109375` for some reason

File: src/openvic-simulation/utility/NumberUtils.hpp [hunk 6]
```diff
@@ -24,4 +24,24 @@ namespace OpenVic::NumberUtils {
 		}
 		return ret;
 	}
+
+	constexpr uint64_t sqrt(uint64_t n) {
```
Comment (wvpm) [inline src/openvic-simulation/utility/NumberUtils.hpp:28]: Does not work.
sqrt of 100.0 (fixed_point_t) gives 0.9999847412109375

**Review by wvpm — CHANGES_REQUESTED** [review]
Please fix and test sqrt

File: src/openvic-simulation/map/Map.cpp (hunk 5 above)
Comment (zaaarf) [reply src/openvic-simulation/map/Map.cpp:80]: oh, right!

**Review by wvpm — APPROVED** [review]

**Review by Hop311 — APPROVED** [review]
Working for me 👍
